development:
  adapter: postgresql
  encoding: unicode
  database: twendy_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: twendy_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: twendy_production
  pool: 5
